import '@/styles/reset.scss'
import '@/styles/global.scss'
import '@/styles/variables.css'
import type { Metadata } from 'next'
import { roboto } from '@/libs/font'
import Header from '@/components/Header'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className + ' ' + 'dark'}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
