export const FooterNavs = [
    {
        id:1,
        title:'Categories',
        navs:[
            {
                id:1,
                value:'User Interface',
                href:'/',
                state:''

            },
            {
                id:2,
                value:'User Experience',
                href:'/',
                state:''

            },
            {
                id:3,
                value:'Digital Media',
                href:'/',
                state:''

            },
            {
                id:4,
                value:'Lifestyle',
                href:'/',
                state:''

            },
        ]
    },
    {
        id:2,
        title:'Product',
        navs:[
            {
                id:5,
                value:'Pricing',
                href:'/',
                state:''
            },
            {
                id:6,
                value:'Overview',
                href:'/',
                state:''
            },
            {
                id:7,
                value:'Browse',
                href:'/',
                state:''
            },
            {
                id:8,
                value:'Accessibility',
                href:'/',
                state:'beta'
            },
        ]
    },
    {
        id:3,
        title:'Solutions',
        navs:[
            {
                id:9,
                value:'Brainstorming',
                href:'/',
                state:''
            },
            {
                id:10,
                value:'Ideation',
                href:'/',
                state:''
            },
            {
                id:11,
                value:'Wireframing',
                href:'/',
                state:''
            },
            {
                id:12,
                value:'Research',
                href:'/',
                state:''
            },
        ]
    },
    {
        id:4,
        title:'Resources',
        navs:[
            {
                id:13,
                value:'Help Center',
                href:'/',
                state:''
            },
            {
                id:14,
                value:'Blog',
                href:'/',
                state:''
            },
            {
                id:15,
                value:'Tutorials',
                href:'/',
                state:''
            },
            {
                id:16,
                value:'FAQs',
                href:'/',
                state:''
            },
        ]
    },
    {
        id:5,
        title:'Support',
        navs:[
            {
                id:17,
                value:'Contact Us',
                href:'/',
                state:''
            },
            {
                id:18,
                value:'Developers',
                href:'/',
                state:''
            },
            {
                id:19,
                value:'Documentation',
                href:'/',
                state:''
            },
            {
                id:20,
                value:'Integrations',
                href:'/',
                state:''
            },
        ]
    },
    {
        id:6,
        title:'Company',
        navs:[
            {
                id:21,
                value:'About',
                href:'/',
                state:''
            },
            {
                id:2,
                value:'Press',
                href:'/',
                state:''
            },
            {
                id:3,
                value:'Events',
                href:'/',
                state:''
            },
            {
                id:4,
                value:'Request Demo',
                href:'/',
                state:''
            },
        ]
    },
]